config/routes.rb
Rails.application.routes.draw do

  get     'signup', to: 'users#new'
  get     'login',  to: 'sessions#new'
  post    'login',  to: 'sessions#create'
  delete  'logout', to: 'sessions#destroy'
  resources :users

  get 'new_question', to: 'questions#new'
  resources :questions

  root 'static_pages#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user_id
  belongs_to :question_id
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { email.downcase! }
	has_many :questions
	has_many :answers

	validates :name, presence: true, length: { maximum: 20 }
	validates :email, presence: true, length: { maximum: 50 }, uniqueness: true

	has_secure_password
	validates :password, length: { minimum: 4 }, allow_blank: true

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def answer_create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
  	@question = Question.new
  end

  def show
  	@question = Question.find(params[:id])
  end

  def create
  	@question = Question.new(question_params)
  	if @question.save
  		flash[:success] = "Question posted!"
  		redirect_to @question
  	else
  		render 'new'
  	end
  end

  private

  def question_params
  	params.require(:question).permit(:title, :question)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in(user)
  		redirect_to root_url
  	else
  		flash.now[:danger] = "Invalid email or password!"
  		render 'new'
  	end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def login
  	@username = ""
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		log_in @user
  		flash[:success] = "Sign up successful!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user unless current_user?(@user)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def current_user?(user)
		user == current_user
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/answer_create.html.erb
<h1>Answers#answer_create</h1>
<p>Find me in app/views/answers/answer_create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NaOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="page-container">
		<nav>
			<ul>
				<li class="logo">
					<%= link_to image_tag("logo.svg", alt: "Next Academy Overflow", width: "35px", height: "35px"), root_path %>
				</li>
				<li>
					<%= link_to 'nextacademy', root_path, class: 'thin' %><%= link_to 'overflow', root_path, class: 'fat' %>
				</li>
				<li class="right">
					<%= link_to 'Log Out', logout_path, method: 'delete'%>
				</li>
				<% if logged_in? %>
				<li class="right">
					<%= link_to current_user.name, edit_user_path(current_user) %>
				</li>
				<% else %>
				<li class="right">
					<%= link_to 'Log In', login_path %>
				</li>
				<li class="right">
					<%= link_to 'Sign Up', signup_path %>
				</li>
				<% end %>
			</ul>
		</nav>
		<% flash.each do |message| %>
			<div><%= message %></div>
		<% end %>
		<%= yield %>
	</div>
	



</body>
</html>

app/views/questions/new.html.erb
<h1>Post New Question</h1>
<div class="form-container">
	<%= form_for(@question) do |f| %>

		<%= f.label :title %>
		<%= f.text_field :title %>

		<%= f.label :question %>
		<%= text_area_tag :question %>

		<%= f.submit 'Post Question', class: 'button' %>
	<% end %>

</div>

app/views/questions/question_create.html.erb
<h1>Questions#question_create</h1>
<p>Find me in app/views/questions/question_create.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div>
		The form contains <%= pluralize(@user.errors.count, "error") %>.
		<ul>
			<% @user.errors.full_messages.each do |message|%>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/index.html.erb
<%= link_to 'Ask Question', new_question_path %>

app/views/static_pages/login.html.erb
<div class="form-container">
  <form action="/login" method="POST">
    <div>username</div>
    <div><input class="input" type="text" name="username" value="<%= @username %>" autofocus></div>
    <div>password</div>
    <div><input class="input" type="password" name="password"></div>
    <div>
      <input type="submit" name="action" value="login" class="button">&nbsp;
      <input type="submit" name="action" value="signup" class="button">
    </div>
  </form>
</div>

app/views/users/edit.html.erb
<h1>Update Profile</h1>
<div class="form-container">
	<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>
		
		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.email_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.label :password_confirmation, 'Confirmation' %>
		<%= f.password_field :password_confirmation %>

		<%= f.submit 'Save Changes', class: 'button' %>
	<% end %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<div class="form-container">
	<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>
		
		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.email_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.label :password_confirmation, 'Confirmation' %>
		<%= f.password_field :password_confirmation %>

		<%= f.submit 'Sign Up', class: 'button' %>
	<% end %>
</div>

app/views/users/show.html.erb
<h1>Users#user_edit</h1>
<p>Find me in app/views/users/user_edit.html.erb</p>

app/views/users/user_edit.html.erb
<h1>Users#user_edit</h1>
<p>Find me in app/views/users/user_edit.html.erb</p>